JDP210303-20 - Encja User - testy
mryndak/jdp-2103-01-backend pull request #17
Opened 2021-04-08 19:35 UTC by GitJanusz

2021-04-09 08:54 UTC, CodingWithR4K3 approved these changes
LGTM!

2021-04-09 11:34 UTC, bartosz-kedziora approved these changes

2021-04-09 18:02 UTC, sitkositkowski requested changes

2021-04-09 18:02 UTC, sitkositkowski commented on src/test/java/com/kodilla/ecommerce/domain/UserTestSuite.java
> +    private final Cart cartTest = new Cart();
Przy jednym requescie z testami pojawił się komentarz od PMa, że dla każdego testu powinien być tworzony nowy obiekt testowy.

2021-04-09 18:09 UTC, CodingWithR4K3 commented on src/test/java/com/kodilla/ecommerce/domain/UserTestSuite.java
> +    private final Cart cartTest = new Cart();
Ale też zatwierdzony został test dla encji Order w którym nie były robione nowe obiekty, także sam już się gubię. Myślę że raczej powinien być robiony nowy obiekt na każdy test ale zarazem w testach dla order jakoś to działa, kwestia czy zostawiać to czy może jednak robić nowy obiekt na każdy test

2021-04-09 18:19 UTC, sitkositkowski commented on src/test/java/com/kodilla/ecommerce/domain/UserTestSuite.java
> +    private final Cart cartTest = new Cart();
Ja bym się skłaniał ku opcji, gdzie obiekty testowe są tworzone wewnątrz każdego testu na nowo. Poprawienie tego w testach dla Order nie powinno być specjalnie czasochłonne

2021-04-09 18:22 UTC, CodingWithR4K3 commented on src/test/java/com/kodilla/ecommerce/domain/UserTestSuite.java
> +    private final Cart cartTest = new Cart();
Też mi się tak wydaje, ze będzie lepiej to zmienić aby były robione na nowo jak w produkcie w każdej metodzie testowej

2021-04-09 18:32 UTC, GitJanusz commented on src/test/java/com/kodilla/ecommerce/domain/UserTestSuite.java
> +    private final Cart cartTest = new Cart();
Uważam, że nie ma takiej potrzeby aby w każdym teście tworzyć nowy obiekt, skoro w każdym teście używamy tej samej nazwy obiektu. Według mnie rozwiązanie przesłane przeze mnie jest bardziej czytelne i przyjazne dla oka ;), dzięki temu nie tworzymy zbędnego kodu. Proponowałbym, aby w tej kwestii wypowiedział się @mryndak

2021-04-12 19:19 UTC, mryndak commented on src/test/java/com/kodilla/ecommerce/domain/UserTestSuite.java
> +    private final Cart cartTest = new Cart();
Każdy test powinien przygotować sobie swoje dane, swoje obiekty itp., a na koniec posprzatać po sobie.

2021-04-12 19:19 UTC, mryndak commented on src/test/java/com/kodilla/ecommerce/domain/UserTestSuite.java
> +    private final Cart cartTest = new Cart();
to co jest w polach powinno polecieć do sekcji given

2021-04-12 19:30 UTC, GitJanusz commented on src/test/java/com/kodilla/ecommerce/domain/UserTestSuite.java
> +    private final Cart cartTest = new Cart();
Dobrze, biorę się za zmianę w testach User oraz Order.

2021-04-13 08:00 UTC, CodingWithR4K3 approved these changes

2021-04-13 08:02 UTC, bartosz-kedziora approved these changes

2021-04-13 09:39 UTC, sitkositkowski approved these changes

2021-04-13 09:41 UTC, merged