Jdp210303 22
mryndak/jdp-2103-01-backend pull request #19
Opened 2021-04-09 11:35 UTC by bartosz-kedziora

2021-04-09 18:03 UTC, sitkositkowski requested changes

2021-04-09 18:16 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private List<CartItem> items = new ArrayList<>();
Moim zdaniem powinny być to obiekty typu DTO, tak samo jak OrderDto ma Listę z OrderItemDto

2021-04-09 18:20 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private List<CartItem> items = new ArrayList<>();
Zgadzam się z przedmówcami, zdecydowanie lepiej będzie pozostać przy obiektach DTO.

2021-04-09 18:23 UTC, GitJanusz requested changes
Bartosz, rozwiąż proszę konflikty.

2021-04-09 18:35 UTC, sitkositkowski requested changes

2021-04-09 18:35 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +
W przypadku kiedy mamy listę produktów Dto (o czym pisałem w poprzednim komentarzu) to można zmienić w ten sposób
```suggestion
    public GroupDto mapToGroupDto(final Group group, final List<ProductDto> products) {
        return new GroupDto(
                group.getGroupId(),
                group.getName(),
                products);
    }

```

2021-04-09 18:35 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +
```suggestion
public class GroupService {

    private final GroupRepository groupRepository;
    private final GroupMapper groupMapper;
    private final ProductMapper productMapper;
    
    public GroupDto fromEtoD(Group group, List<Product> products){
        List<ProductDto> productsDto = productMapper.mapToDto(products);
        return groupMapper.mapToDto(group, productsDto);
    }
```

2021-04-09 18:36 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private List<CartItem> items = new ArrayList<>();
Poniżej podałem sugestie dot. przejścia na Dto. Dajcie znać pod nimi co sądzicie i jakie macie pomysły

2021-04-11 14:06 UTC, bartosz-kedziora commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private List<CartItem> items = new ArrayList<>();
Faktycznie zostańmy przy obiektach typu DTO

2021-04-13 18:38 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
```suggestion
    public GroupDto mapToGroupDto(final Group group) {
        List<Product> products = group.getProducts();
        List<ProductDto> productsDto = new ArrayList<>();
        for(Product product: products){
            productsDto.add(new ProductDto(product.getId(), product.getName(), product.getDescription(), product.getPrice(), product.getGroupId()));
        }
        return new GroupDto(
                group.getGroupId(),
                group.getName(),
                productsDto);
    }
```

2021-04-13 18:38 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
to drugi pomysł na rozwiązanie tego problemu z mapperami i Dto

2021-04-13 18:38 UTC, sitkositkowski commented
@bartosz-kedziora @CodingWithR4K3 @GitJanusz wypowiedzcie się co sądzicie o podejściu do mapperów

2021-04-14 09:43 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Dla mnie spoko rozwiązanie, jestem za tym aby tak to zastosować

2021-04-14 10:57 UTC, bartosz-kedziora commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Będę próbował to ogarnać

2021-04-14 11:02 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Również uważam, że jest to dobry pomysł

2021-04-14 11:21 UTC, bartosz-kedziora commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
gdy próbuje dodać product.getGroupId() lub product.getGroup().getGroupId()) w linii 26 do konstruktora ProductDto to wyskakuje mi błąd: 'ProductDto(java.lang.Long, java.lang.String, java.lang.String, java.math.BigDecimal, java.lang.Long)' is not public in 'com.kodilla.ecommerce.dto.ProductDto'. Cannot be accessed from outside package.

2021-04-14 12:22 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
to dlatego, że w klasie ProductDto brakuje adnotacji @AllArgsConstructor. Możesz dodać ją i @NoArgsConstructor lub spróbować zrobić to przy użyciu buildera. Ja byłbym za pierwszą opcją

2021-04-14 14:07 UTC, sitkositkowski commented
Wygląda spoko, ale myślę, że jutro na spotkaniu przegadamy jeszcze raz podejście do implementacji metod dla wszystkich controllerów.

2021-04-14 14:08 UTC, sitkositkowski reviewed
Wygląda spoko, ale myślę, że jutro na spotkaniu przegadamy jeszcze raz podejście do implementacji metod dla wszystkich controllerów.

2021-04-16 16:23 UTC, GitJanusz requested changes

2021-04-16 16:23 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +            group.ifPresent(g -> g.setName(groupDto.getName()));
Wydaje mi się, że w tym miejscu powinna być wywołana powyższa metoda "saveGroup", ponieważ zmiany niezostaną zapisane.

2021-04-16 16:25 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +            group.ifPresent(g -> g.setName(groupDto.getName()));
Ale jest setName

2021-04-16 16:32 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +            group.ifPresent(g -> g.setName(groupDto.getName()));
Właśnie wiem, ale przy produkcie kompletnie mi to nie działa.. :/

2021-04-16 16:49 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +            group.ifPresent(g -> g.setName(groupDto.getName()));
@bartosz-kedziora przetestuj proszę update i daj znać, czy po znalezieniu grupy po id zmiany zostały zapisane.

2021-04-16 18:59 UTC, GitJanusz submitted a review, later dismissed

2021-04-16 18:59 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
>      }
Metoda nie działa poprawnie, ponieważ mimo tego, że jest "setName" zmiany nie są widoczne przy wyszukaniu grupy po id.

2021-04-19 16:30 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/CartService.java
> +    }
zmień productId na cartItemId czy coś takiego

2021-04-19 16:30 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/CartService.java
> +    }
tutaj również zmiana nazw id i zmiana nazwy metody na removeItemFromCart

2021-04-19 16:30 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/CartService.java
> +    }
zgodnie z podejściem, że każdy koszyk jest tworzony przy tworzeniu użytkownika (jedyna możliwość) to metoda jest zbędna

2021-04-19 16:30 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +}
Relacja grupy z produktami zawiera Cascade.ALL, wiec ta metoda spowoduje usunięcie wszystkich produktów danej grupy jednoczenie

2021-04-19 16:30 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +public class GroupService {
brakuje mi metody, która dodaje produkty do grupy

2021-04-19 20:54 UTC, bartosz-kedziora commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +}
To może ta metoda jest zbędna?

2021-04-20 13:23 UTC, CodingWithR4K3 approved these changes

2021-04-20 16:38 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +        return Optional.empty();
co się dzieje w przypadku gdy nie ma produktu o danym id?

2021-04-21 09:10 UTC, sitkositkowski approved these changes

2021-04-21 09:27 UTC, sitkositkowski commented
Coś namieszałem przy rozwiązywaniu konfliktów

2021-04-21 09:49 UTC, sitkositkowski commented
Sorry za kłopot, rozwiąż konflikty i możemy zmergować

2021-04-21 10:49 UTC, merged