JDP210303-21 - ProductController - rzeczywista implementacja metod
mryndak/jdp-2103-01-backend pull request #22
Opened 2021-04-19 19:38 UTC by GitJanusz

2021-04-20 16:35 UTC, sitkositkowski requested changes

2021-04-20 16:35 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/ProductService.java
> +    }
dodałbym tutaj jakiś element, który pozwoliłby dodać grupę do Productu. Coś w stylu:

`Optional<Group> group = groupRepository.findById(productDto.getGroupId())`

2021-04-20 16:35 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/service/ProductService.java
> +    }
Brak możliwości zmiany grupy

2021-04-21 05:48 UTC, sitkositkowski approved these changes

2021-04-21 09:12 UTC, CodingWithR4K3 approved these changes

2021-04-21 09:12 UTC, merged