JDP210303-4 - OrderController
mryndak/jdp-2103-01-backend pull request #3
Opened 2021-03-31 09:46 UTC by GitJanusz

2021-03-31 10:23 UTC, mryndak requested changes

2021-03-31 10:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +@AllArgsConstructor
Jeszcze ```@NoArgsConstructor``` bo będzie problem z serializacja / deserializacją JSONa

2021-03-31 10:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +@AllArgsConstructor
Można też dodać ```@Builder``` - powstanie nam builder, będzie łatwiej działać w mapperach :)

2021-03-31 10:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private String status;
Dla statusu zamówienia proponował bym wprowadzić typ wyliczeniowy (enum)

2021-03-31 10:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private Long productId;
widziałbym tutaj bardziej listę produktów, niż pojedyczne id produktu (klient może do koszyka dodać kilka produktów)
widziałbym tutaj też pole z wartością zamówienia, adresem wysyłki.

2021-03-31 10:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +@RequestMapping(value = "/v1/order", consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
"/v1/orders"

2021-03-31 10:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @GetMapping(value = "orders")
value jest tutaj niepotrzebne

2021-03-31 10:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    public OrderDto getOrder(@RequestParam Long id) {
w ProductController został użyty  ```@PathVariable``` - proponowałbym aby tutaj też był użyty i by endpointy były spójne co do swojej konstrukcji

2021-03-31 10:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    public void deleteOrder(@RequestParam Long id) {
jw ```@PathVariable````

2021-03-31 17:28 UTC, mryndak requested changes

2021-03-31 17:28 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private List<Product> products;
powinno być List<ProductDto> albo coś innego - jak myślisz co by to mogło być? bo brakuje mi ilości zamówionych produktów - zakładam, że dany produkt może być kupiony w wielu sztukach w jednym zamówieniu

2021-03-31 18:55 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private List<Product> products;
Myślę, że mógłbym zastosować HashMap, gdzie kluczem byłby produkt, a wartością ilość typu Integer.

2021-03-31 19:00 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private List<Product> products;
Tak można by, ale można by było też wprowadzić sobie dodatkowy obiekt np. OrderItem, który to miałby w sobie obiekt produktu i ilość zakupionego produktu - wydaje mi się, że byłoby prościej, ale sam zdecyduj :)

2021-03-31 19:05 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private List<Product> products;
Słuszna uwaga! Twoje rozwiązanie jest zdecydowanie lepsze, zabieram się za poprawianie. :)

2021-03-31 21:32 UTC, CodingWithR4K3 requested changes

2021-03-31 21:32 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/dto/OrderItem.java
> +public class OrderItem {
Moim zdaniem OrderItem powinien też posiadać id. Można by też dopisać Dto do nazwy jeśli nim jest :)

2021-04-01 07:34 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/dto/OrderItem.java
> +public class OrderItem {
Również przez chwilę o tym myślałem i myślę, że skoro OrderItem będzie Dto, to powinienem zrobić z niego również encje.

2021-04-01 07:36 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/dto/OrderItem.java
> +public class OrderItem {
Dokładnie tak, sam OrderItem bedzie encją :)
Reszta wszystko super!

2021-04-01 07:39 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/dto/OrderItem.java
> +public class OrderItem {
Jak narazie to zadanie do endpointów wiec DTO styknie takie :)

2021-04-01 08:46 UTC, CodingWithR4K3 approved these changes

2021-04-01 09:00 UTC, mryndak requested changes

2021-04-01 09:00 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/OrderItemDto.java
> +    private List<Product> product;
nie List, tylko ProductDto lub productId

2021-04-01 09:00 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private OrderItemDto items;
```List<OrderItemDto> items; ```

2021-04-01 10:37 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/controller/enums/StatusOrder.java
> +public enum StatusOrder {
Myślę, że bardziej pasują statusy w pakiecie domain niż w controllerze

2021-04-01 12:41 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/controller/enums/StatusOrder.java
> +public enum StatusOrder {
Właśnie miałem dylemat gdzie je zamieścić. Widzę, że oboje z Karolem jesteście za tym, aby umieścić w pakiecie domain, więc już poprawiam.

2021-04-01 12:44 UTC, CodingWithR4K3 approved these changes
Jest super :)

2021-04-01 12:45 UTC, GitJanusz commented
Dzięki, pytanie - co na to mentor? :D

2021-04-01 13:56 UTC, mryndak approved these changes

2021-04-01 14:03 UTC, merged