JDP210303-5 - UserController
mryndak/jdp-2103-01-backend pull request #4
Opened 2021-03-31 22:17 UTC by sitkositkowski

2021-03-31 23:01 UTC, CodingWithR4K3 requested changes

2021-03-31 23:01 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +    private String status;
Dla statusu można by zrobić typ wyliczeniowy enum :)

2021-04-01 08:26 UTC, GitJanusz requested changes

2021-04-01 08:26 UTC, GitJanusz commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +@AllArgsConstructor
Dodaj jeszcze adnotację "@NoArgsConstructor" ponieważ będzie problem z serializacja / deserializacją JSONa

2021-04-01 09:51 UTC, CodingWithR4K3 requested changes

2021-04-01 09:51 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    @GetMapping(value = "/{userId}")
Value jest tutaj niepotrzebne jak i w poniższych przypadkach

2021-04-01 09:51 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +    public enum Status{BLOCKED_USER, ACTIVE_USER};
Sugeruję aby zrobić enum jako osobną klasę jak w StatusOrder w OrderController

2021-04-01 10:02 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    @GetMapping(value = "/{userId}")
mamy dwa razy @GetMapping oraz @PutMapping

2021-04-01 10:14 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +    public enum Status{BLOCKED_USER, ACTIVE_USER};
ok, pytanie czy nie lepszy byłby folder w pakiecie domain niż controller jak w przypadku StatusOrder

2021-04-01 10:15 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    @GetMapping(value = "/{userId}")
co do createUser się zgadzam

2021-04-01 10:31 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    @GetMapping(value = "/{userId}")
Bez value w sensie myślę o @GetMapping ("/{userId}")

2021-04-01 10:31 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +    public enum Status{BLOCKED_USER, ACTIVE_USER};
Myślę, że lepiej w domain, bardziej ma sens

2021-04-01 12:36 UTC, CodingWithR4K3 requested changes

2021-04-01 12:36 UTC, CodingWithR4K3 commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    @PutMapping("blockUser")
Tutaj na początku powinny być ukośniki tak myślę, w sensie `("/blockUser")` i to samo z generateUserKey

2021-04-01 12:41 UTC, CodingWithR4K3 approved these changes

2021-04-01 12:43 UTC, CodingWithR4K3 commented
Looks good to me! :)

2021-04-01 13:55 UTC, mryndak requested changes

2021-04-01 13:55 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    @PutMapping("blockUser")
```/block```
po prostu

2021-04-01 13:55 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    public void generateUserKey(@RequestBody UserDto userDto){
tutaj bym przekazał sobie id user i w response wygenerowany klucz, lub obiekt dto

2021-04-01 13:55 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    public void createUser(@RequestBody UserDto userDto) {
w response UserDto z uzupełnionymi danymi usera (min. id zostanie uzupełnione)

2021-04-01 21:37 UTC, CodingWithR4K3 approved these changes

2021-04-02 11:19 UTC, GitJanusz approved these changes

2021-04-02 14:28 UTC, mryndak requested changes

2021-04-02 14:28 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    public UserDto generateUserKey(@PathVariable Long id){
zrobił bym /{id}/key

2021-04-02 14:28 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +    public UserDto generateUserKey(@PathVariable Long id){
w opisie mamy, że ten token ma się generować po podaniu danych użytkownika, więc można by było tutaj przekazać login usera

2021-04-02 19:35 UTC, mryndak approved these changes

2021-04-02 19:35 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/UsersController.java
> +                .userKey(10001L)
nie wiem, czy nie powinien być to tekst, ale najwyżej będzie typ do zmiany :)

2021-04-02 19:35 UTC, merged