JDP210303-13 - Encja Group
mryndak/jdp-2103-01-backend pull request #8
Opened 2021-04-02 07:17 UTC by bartosz-kedziora

Rename a table from a "groups" to a "product group" in Group file

2021-04-02 09:43 UTC, CodingWithR4K3 approved these changes

2021-04-02 10:51 UTC, GitJanusz approved these changes

2021-04-02 14:29 UTC, mryndak requested changes

2021-04-02 14:29 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +package com.kodilla.ecommerce.repository;public interface GroupRepository {
enter

2021-04-02 14:29 UTC, mryndak commented on src/test/java/com/kodilla/ecommerce/domain/GroupTest.java
> +package com.kodilla.ecommerce.domain;public class GroupTest {
enter

2021-04-03 11:27 UTC, CodingWithR4K3 approved these changes

2021-04-03 11:48 UTC, GitJanusz approved these changes

2021-04-03 13:52 UTC, mryndak requested changes

2021-04-03 13:52 UTC, mryndak commented on src/test/java/com/kodilla/ecommerce/domain/GroupTest.java
> +    public void SaveGroup() {
nazwa testu nie jest poprawna

2021-04-03 13:52 UTC, mryndak commented on src/test/java/com/kodilla/ecommerce/domain/GroupTest.java
> +    public void GroupSetName() {
tutaj również nazwa testu

2021-04-07 08:58 UTC, CodingWithR4K3 reviewed
Dlaczego dodajesz Test do pr z encjami? Już jest pr otwarty z testem

2021-04-07 09:00 UTC, bartosz-kedziora commented
> Dlaczego dodajesz Test do pr z encjami? Już jest pr otwarty z testem

Dziś to pozmieniam, mój błąd.

2021-04-07 09:01 UTC, CodingWithR4K3 commented
Poza tym jest w porzadku na mojego oko :)

2021-04-07 12:11 UTC, CodingWithR4K3 commented
Tutaj też circleCi nie buduje, dziwna sprawa bo u mnie jest okej jakoś

2021-04-07 15:37 UTC, sitkositkowski commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    private List<Product> products = new ArrayList<>();
Brakuje adnotacji @Builder.Default

2021-04-08 09:54 UTC, bartosz-kedziora commented
W circleCi zbudowało poprawnie

2021-04-08 14:38 UTC, mryndak approved these changes

2021-04-08 14:38 UTC, merged