JDP210303-18 - Encja Group - testy
mryndak/jdp-2103-01-backend pull request #9
Opened 2021-04-02 09:34 UTC by bartosz-kedziora

Create class GroupTest and interface GroupRepository

2021-04-02 09:45 UTC, CodingWithR4K3 approved these changes
Według mnie spoko test :)

2021-04-02 10:58 UTC, GitJanusz approved these changes
Według mnie również wszystko w porządku. :)

2021-04-02 14:31 UTC, mryndak requested changes

2021-04-02 14:31 UTC, mryndak commented on src/test/java/com/kodilla/ecommerce/domain/GroupTest.java
> +    Group groupTest = new Group();
dla każdego testu powinniśmy przygotować obiekt, który będziemy testować, więc to pole powinno zniknąć z tego miejsca :)

2021-04-02 14:31 UTC, mryndak commented on src/test/java/com/kodilla/ecommerce/domain/GroupTest.java
> +        assertTrue(groupRepository.existsById(groupTestId));
sprawdziłbym także, czy hibernate ustawił nam id

2021-04-02 14:31 UTC, mryndak commented on src/test/java/com/kodilla/ecommerce/domain/GroupTest.java
> +    public void SetNameGroup() {
nazwa testu jest niepoprawna

2021-04-07 08:53 UTC, CodingWithR4K3 approved these changes
Dla mnie już w porządku :)

2021-04-08 14:38 UTC, mryndak approved these changes

2021-04-08 14:52 UTC, merged